# This is a basic workflow to help you get started with Actions

name: LLVM-CICD

# Controls when the workflow will run 
on:
  push:  
    branches: [ "main" ]     
  pull_request:
    branches: [ "main" ]    
  workflow_dispatch:

jobs:
  LLVM_build:
    strategy:
      matrix:
        arch: [arm64]
    runs-on: ${{ matrix.arch == 'x86' && 'arc-runner-set-x86' || 'arc-runner-set-ampere' }}

    steps:
      - name: Log Operating System Details
        run: |
          echo "Architecture: ${{ matrix.arch }}"
          uname -a
          lsb_release -a || cat /etc/os-release
          lscpu
      
      - name: Checkout LLVM source code
        uses: actions/checkout@v4
        with:
          repository: ampere-solution/llvm-project
          path: llvm-project

      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build python3

      - name: Configure LLVM build
        run: |
          mkdir -p llvm-project/build
          cd llvm-project/build
          cmake -G Ninja \
            -DLLVM_ENABLE_PROJECTS="clang" \
             -DLLVM_ENABLE_RUNTIMES="libunwind;libcxx;libcxxabi" \
            -DLLVM_TARGETS_TO_BUILD="AArch64;X86" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            ../llvm

      - name: Build LLVM
        run: |
          pwd
          cd llvm-project/build
          ninja
        env:
          LLVM_PARALLEL_COMPILE_JOBS: ${{ matrix.arch == 'x86' && 8 || 8 }}

      - name: Commit changes
        env: 
          CI_COMMIT_MESSAGE: Continuous Integration Build Artifacts
          CI_COMMIT_AUTHOR: tinguyen-ampere
        run: |
          pwd
          cd llvm-project
          ls -la
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "tinguyen@amperecomputing.com"
          git add ./build -f
          git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"

      # - name: Push changes
      #   env: 
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #   run: |
      #     cd llvm-project
      #     git push https://${{ secrets.GITHUB_TOKEN }}@github.com/ampere-solution/llvm-project.git HEAD:main
      #     shell: bash
      - name: Verify GITHUB_TOKEN
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Testing GITHUB_TOKEN permissions..."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               https://api.github.com/repos/${{ github.repository }}
          
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pwd
          cd llvm-project
          pwd
          git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/llvm-project.git
          git pull origin main --rebase
          git push origin HEAD:main
      #- name: Push changes
      #  uses: ampere-solution/llvm-project@master
      #  with:
      #    github_token: ${{ secrets.GITHUB_TOKEN }}
        
        

      - name: Display build information
        run: |
          echo "Architecture: ${{ matrix.arch }}"
          echo "Build completed on $(date)"
  deploy:
    needs: LLVM_build
    strategy:
      matrix:
        arch: [arm64]
    runs-on: arc-runner-set-ampere

    steps:
      #- name: List root directory contents
      #  run: |
      #    pwd
      #    ls -la 
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: ampere-solution/llvm-project
          path: llvm-project

      - name: List repository contents
        run: |
          pwd
          ls -la $GITHUB_WORKSPACE
      - name: Set up build environment
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential cmake ninja-build python3

      - name: Configure LLVM build
        run: |
          mkdir -p llvm-project/build
          cd llvm-project/build
          cmake -G Ninja \
            -DLLVM_ENABLE_PROJECTS="clang" \
             -DLLVM_ENABLE_RUNTIMES="libunwind;libcxx;libcxxabi" \
            -DLLVM_TARGETS_TO_BUILD="AArch64;X86" \
            -DCMAKE_BUILD_TYPE=Release \
            -DLLVM_ENABLE_ASSERTIONS=ON \
            ../llvm

      - name: Build LLVM
        run: |
          pwd
          cd llvm-project/build
          ninja
        env:
          LLVM_PARALLEL_COMPILE_JOBS: ${{ matrix.arch == 'x86' && 8 || 8 }}
      - name: install LLVM
        run: |
          pwd
          ls -la
          cd llvm-project/build
          sudo ninja install
        env:
          LLVM_PARALLEL_COMPILE_JOBS: ${{ matrix.arch == 'x86' && 8 || 8 }}

      - name: Verify the installation
        run: |
          clang --version
          llvm-config --version
          

      #- name: Deploy LLVM binaries
      #  run: |
      #    sudo apt update -y
      #    sudo apt install openssh-client -y
      #    scp -r build/bin/* ampere@192.168.10.10:/home/ampere/deployment






      
